### ISSUE TITLE
No banner ad is shown with "Ad failed to load with error code 3" message

### ISSUE THREAD

**Issue by 4ntoine** [HMS-Core/hms-ads-demo-java#10]
Testing on Huawei device with HMS core 5.

Failed to show an ad banner of size SIZE_SMART with "Ad failed to load with error code 3" message:
![device-2021-01-12-234544](https://user-images.githubusercontent.com/846671/104358934-e729ce80-5530-11eb-8ded-2df771ca27fd.png)

The other sizes can be loaded:
![device-2021-01-12-234645](https://user-images.githubusercontent.com/846671/104358951-ec871900-5530-11eb-8649-623a7d47fb58.png)

In the log i can see:
> onAdFailed, errorCode:700

Log file 
[ads_size_smart.txt.zip](https://github.com/HMS-Core/hms-ads-demo-java/files/5804161/ads_size_smart.txt.zip)

**Comment by 4ntoine** [comment]
Also the question: where can one find error codes explanation? eg. SO question https://stackoverflow.com/questions/65689978/what-huawei-adskit-adlistener-onadfailed-errorcode-2-means.
There's nothing [in the doc](https://developer.huawei.com/consumer/en/doc/development/HMS-References/ads-api-adlistener#onAdFailed).

**Comment by Mike-mei** [comment]
Can you provide your complete log? 
You can run this command to return the complete log, ```adb pull /sdcard/Android/data/com.huawei.hwid/files/Log/HiAdKitLog.log ./.```

**Comment by 4ntoine** [comment]
@Mike-mei Thanks for replying.

There's no `HiAdKitLog.log` there:
<img width="353" alt="Снимок экрана 2021-01-13 в 12 23 42" src="https://user-images.githubusercontent.com/846671/104419374-335d2900-559a-11eb-967f-c66be4d2c6b9.png">

HMS core version is "5.0.5.300"

Here are the files:
[hw-logs.zip](https://github.com/HMS-Core/hms-ads-demo-java/files/5807014/hw-logs.zip)

**Comment by Mike-mei** [comment]
@4ntoine The log you provided does not contain the info we need. Could you please provide the Logcat log which contain the error information?

**Comment by 4ntoine** [comment]
@Mike-mei sure, today late evening or early tomorrow

**Comment by 4ntoine** [comment]
@Mike-mei [2021-01-14 22:47:24.739 1377-1544 V:ActivityManage.zip](https://github.com/HMS-Core/hms-ads-demo-java/files/5816114/2021-01-14.22.47.24.739.1377-1544.V.ActivityManage.zip)

**Comment by chenqiuwei** [comment]
Because the dpi of this phone is low, it is 320. and test slotid cannot obtain the ad of the corresponding size.
Maybe you could use a high-resolution phone to test it.
or set the resolution of your phone following this way: Settings > Display > Screen resolution , and select FHD+, and try again.

**Comment by 4ntoine** [comment]
@chenqiuwei Not sure i understand, i understand SMART_BANNER as banner size that adjusts to the devices specs (eg. screen size), no special size (layout_width, layout_height) is set in the app for it as far as i can see. Also 320x100 is shown successfully, and it's a bit surprising why not just fall down to it.

I'm testing on Honor 9S and i can't find the setting.

Are there any requirements/recommendations for ad banners sizes per density, screen size, etc in order to avoid the issues like that?

**Comment by chenqiuwei** [comment]
https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides-V5/publisher-service-banner-0000001050066915-V5#EN-US_TOPIC_0000001057202899__section2706194414318
Screen Height of Honor 9S is 480dp (720x1440), it should return 720x100dp ad materials, no ad is returned because no test task of this size is launched.

**Comment by 4ntoine** [comment]
@chenqiuwei i'm not sure i want to dive into details on how it works inside. Can you give advices on when should it be used? It was expected that it's more efficient than just 1 hard-coded as size. Should i detect screen density (probably just use default android "per-something" mechanism) and switch to another ad banner size? If yes, what are the other cases that should be covered?

**Comment by chenqiuwei** [comment]
As described in the development document, the Smart banner determines the ad size based on the screen height of the phone. In this case, the ad size may be different. Sometimes, the ad task may not cover so many sizes. I recommend using a fixed size such as BANNER_SIZE_320_50.

Thanks.
