### ISSUE TITLE
Adding keywords breaks the JSON

### ISSUE THREAD

**Issue by 4ntoine** [HMS-Core/hms-ads-demo-java#11]
See SO question and answer: https://stackoverflow.com/questions/65689978/what-huawei-adskit-adlistener-onadfailed-errorcode-2-means

**Comment by Mike-mei** [comment]
We'll look at your changes, thank you for your contribution.

**Comment by 4ntoine** [comment]
Any merge landed to fix it or API+documentation updated?

**Comment by Mike-mei** [comment]
Thank you for your reply. We will add the info in the documentation before the end of February, and this issue will be fixed asap.
