### ISSUE TITLE
原生广告控件，不再显示该广告按钮无法显示

### ISSUE THREAD

**Issue by kaihavice** [HMS-Core/hms-ads-demo-java#12]
已使用最新的13.4.40.301版本,包括下载GitHub最新的demo都有这个问题，请修复。

**Comment by chenqiuwei** [comment]
@kaihavice 如果您的设备是中国版本的，默认不显示“不再显示该广告”按钮，只有海外版的设备才会显示。

**Comment by kaihavice** [comment]
> @kaihavice 如果您的设备是中国版本的，默认不显示“不再显示该广告”按钮，只有海外版的设备才会显示。

好的
