### ISSUE TITLE
from where i get the id ads?

### ISSUE THREAD

**Issue by ibrha** [HMS-Core/hms-ads-demo-java#3]
hi where i can find id ads like admob id adverist ca-app/xxxxxxxxxxx-xxxxxxxx
because i need change them with real ads not test ads ?? give me the url please and thank you

**Comment by chenqiuwei** [comment]
Go to https://developer.huawei.com/consumer/en/monetize/ and click "Start now", then go to HUAWEI Ads Publisher Console
https://developer.huawei.com/consumer/en/service/ads/publisher/html/index.html?lang=en
apply real ad unit id.
