### ISSUE TITLE
APK link for the Ads Demo

### ISSUE THREAD

**Issue by mwshubham** [HMS-Core/hms-ads-demo-java#4]
Hi team,

Can we have support to automatically generate APK file for each release of this demo project via Github Actions.

This will help the developers to review the APK directly without going into building the entire project.

Regards,
Shubham

**Comment by ferPrieto** [comment]
Hey @mwshubham, you will be able to see an updated **apk** generated in this repo (please you check in Code/releases) from the latest build available in master. Let me know if you have any issue and thanks for your suggestion.

**Comment by mwshubham** [comment]
Thanks.
