### ISSUE TITLE
Can screenshots be added to the Readme page?

### ISSUE THREAD

**Issue by halilozel1903** [HMS-Core/hms-ads-demo-java#6]
Hi,

Can screenshots be added to the Readme page?

If there are screenshots, more detailed information about the project will be provided.

Happy coding

**Comment by Mike-mei** [comment]
@halilozel1903 
Thank you for your advice, we have added the screenshot gif of each Ads into Readme and it looks better now.

**Comment by halilozel1903** [comment]
It's looking nice 👍🏻
