### ISSUE TITLE
No banner ad is shown with "Ad failed to load with error code 0" message

### ISSUE THREAD

**Issue by 4ntoine** [HMS-Core/hms-ads-demo-java#8]
I've cloned, compiled and launched the demo app on ZTE device with HMS Core 5.0.2.301 (apk) downloaded and installed manually.

I can't see any banner shown, but i can see "Ad failed to load with error code 0" toast instead:

![device-2021-01-06-005354](https://user-images.githubusercontent.com/846671/103692871-3e242680-4fba-11eb-9693-0cf9e19dd6ad.png)

![device-2021-01-06-005608](https://user-images.githubusercontent.com/846671/103692883-42e8da80-4fba-11eb-925a-70ec8aa21bba.png)

Here is the full log file attached. 
[adkit.log.txt.zip](https://github.com/HMS-Core/hms-ads-demo-java/files/5772307/adkit.log.txt.zip)

Let me know if i did anything wrong.

PS.
ZTE Blade V8
Android 7.0

**Comment by chenqiuwei** [comment]
Try to change the country/region in your phone to other countries, don't set to US.

Thanks.

**Comment by 4ntoine** [comment]
Id did not help - I've tried to set language to "English (UK)" and "French" and got "Ad failed to load with error code 3" in all the case.

**Comment by chenqiuwei** [comment]
You can use a HUAWEI Phone to test, and if you are connected to a network from US, pls try use VPN to connect to another country. HUAWEI Ads don't advertise to users from US.

Following the development guide:
https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/publisher-service-dev-process-0000001050064964

Thanks.

**Comment by 4ntoine** [comment]
I thought it does not require Huawei phone, but just any phone with HMS
core apk installed. Can you clarify if it is expected to work on non-Huawei
devices?

пт, 8 янв. 2021 г., 06:23 chenqiuwei <notifications@github.com>:

**Comment by chenqiuwei** [comment]
Yes. Currently, only Huawei devices are supported.

**Comment by 4ntoine** [comment]
@chenqiuwei thanks for clarification
