### ISSUE TITLE
有没有办法获取真实广告而不是Test广告？

### ISSUE THREAD

**Issue by jiaohaibin** [HMS-Core/hms-ads-demo-java#9]
有没有办法获取真实广告而不是Test广告？想评估一下华为广告平台的广告质量。或者有现有市场里面哪个app是展示华为广告的可以告知一下吗？

**Comment by chenqiuwei** [comment]
可以使用 华为视频/华为音乐/华为阅读等APP，可以获取到真实广告。

**Comment by jiaohaibin** [comment]
感谢答复
